apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sctp
  template:
    metadata:
      name: sctp
      labels:
        app: sctp
    spec:
      containers:
        - name: sctp
          image: tacobayle/sctp_server
          ports:
            - containerPort: 3868
              protocol: SCTP
      restartPolicy: Always
