apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web2
spec:
  rules:
    - host: web2.vcenter.avi.com
      http:
        paths:
          - backend:
              serviceName: web-front-2
              servicePort: 80
            path: /