apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: secure-web-front-3
spec:
  tls:
  - hosts:
     - tlsweb3.vcenter.avi.com
    secretName: cert1

  rules:
    - host: tlsweb3.vcenter.avi.com
      http:
        paths:
          - backend:
              serviceName: web-front3
              servicePort: 80
            path: /
