apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web3
spec:
  rules:
    - host: web3.vcenter.avi.com
      http:
        paths:
          - backend:
              serviceName: web-front-3
              servicePort: 80
            path: /