apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: secure-web-front-1
spec:
  tls:
  - hosts:
     - tlsweb.vcenter.avi.com
    secretName: cert1

  rules:
  - host: tlsweb1.vcenter.avi.com
    http:
      paths:
        - backend:
              serviceName: web-front1
              servicePort: 80
            path: /
