apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web1
spec:
  rules:
    - host: web1.vcenter.avi.com
      http:
        paths:
          - backend:
              serviceName: web-front-1
              servicePort: 80
            path: /