apiVersion: v1
kind: Service
metadata:
  name: web-front-nodeport-2
spec:
  type: NodePort
  selector:
    app: web-front2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082