apiVersion: v1
kind: ConfigMap
metadata:
  name: json-configmap
  namespace: default
data:
  variables.json: |
    {
      "vcenter_underlay": {
        "dc": "sof2-01-vc08",
        "cluster": "sof2-01-vc08c01",
        "datastore": "sof2-01-vc08c01-vsan",
        "resource_pool": "sof2-01-vc08c01/Resources",
        "folder": "nic-vSphere8-NSX-Avi",
        "server": "sof2-01-vc08.oc.vmware.com",
        "networks": {
          "vsphere": {
            "management": {
              "name": "vxw-dvs-34-virtualwire-3-sid-1080002-sof2-01-vc08-avi-mgmt"
            },
            "vmotion": {
              "name": "vxw-dvs-34-virtualwire-120-sid-1080119-sof2-01-vc08-avi-dev116"
            },
            "vsan": {
              "name": "vxw-dvs-34-virtualwire-119-sid-1080118-sof2-01-vc08-avi-dev115"
            }
          },
          "nsx": {
            "external": {
              "name": "vxw-dvs-34-virtualwire-124-sid-1080123-sof2-01-vc08-avi-dev120"
            },
            "overlay": {
              "name": "vxw-dvs-34-virtualwire-125-sid-1080124-sof2-01-vc08-avi-dev121"
            },
            "overlay_edge": {
              "name": "vxw-dvs-34-virtualwire-126-sid-1080125-sof2-01-vc08-avi-dev122"
            }
          }
        }
      }
    }
