apiVersion: v1
kind: Service
metadata:
  name: web1
  annotations:
    ako.vmware.com/load-balancer-ip: "192.168.201.14"
spec:
  loadBalancerClass: ako.vmware.com/avi-lb
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: eighty
  selector:
    app: app-selector-v1