apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: my-host-rule1
  namespace: default
spec:
  virtualhost:
    enableVirtualHost: true
    wafPolicy: System-WAF-Policy
    tls:
      sslKeyCertificate:
        name: System-Default-Cert-EC
        type: ref
    analyticsPolicy:
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true
    fqdn: v1.mydomain.com
---
apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: my-host-rule2
  namespace: default
spec:
  virtualhost:
    enableVirtualHost: true
    wafPolicy: System-WAF-Policy
    tls:
      sslKeyCertificate:
        name: System-Default-Cert-EC
        type: ref
    analyticsPolicy:
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true
    fqdn: v2.mydomain.com
---
apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: my-host-rule3
  namespace: default
spec:
  virtualhost:
    enableVirtualHost: true
    wafPolicy: System-WAF-Policy
    tls:
      sslKeyCertificate:
        name: System-Default-Cert-EC
        type: ref
    analyticsPolicy:
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true
    fqdn: v3.mydomain.com