apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-http-app-v3-np
spec:
  parentRefs:
    - name: gw-multiple-listeners
  hostnames:
    - "gw-v3-np.mydomain.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: svc-v3-np
          port: 80