apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-http-app-v1
spec:
  parentRefs:
    - name: my-gateway
  hostnames:
    - "v1.mydomain.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: svc-v1
          port: 80