apiVersion: ako.vmware.com/v1alpha1
kind: RouteBackendExtension
metadata:
  name: my-route-backend-extension
  namespace: default
spec:
  # Load balancing configuration
  lbAlgorithm: LB_ALGORITHM_CONSISTENT_HASH
  lbAlgorithmHash: LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_HEADER
  lbAlgorithmConsistentHashHdr: "X-Forwarded-For"

  # Session persistence configuration
  persistenceProfile: System-Persistence-Client-IP

  # Backend TLS/SSL configuration
  backendTLS:
    hostCheckEnabled: true
    domainName:
      - "app.mydomain.com"