apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: my-host-rule-route-2
  namespace: default
spec:
  virtualhost:
    enableVirtualHost: true
    wafPolicy: System-WAF-Policy
    tls:
      sslKeyCertificate:
        name: System-Default-Cert-EC
        type: ref
    analyticsPolicy:
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true
    fqdn: route2.mydomain.com