apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-http-app-v3
spec:
  parentRefs:
    - name: gw-multiple-listeners
  hostnames:
    - "gw-v3.mydomain.com"
  rules:
    - filters:
        - type: ExtensionRef
          extensionRef:
            group: ako.vmware.com
            kind: L7Rule
            name: gw-sec
      matches:
          - path:
              type: PathPrefix
              value: /
      backendRefs:
        - name: svc-v3
          port: 80
          filters:
            - type: ExtensionRef
              extensionRef:
                group: ako.vmware.com
                kind: HealthMonitor
                name: my-health-monitor
            - type: ExtensionRef
              extensionRef:
                group: ako.vmware.com
                kind: RouteBackendExtension
                name: my-route-backend-extension