apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: my-host-rule1
  namespace: default
spec:
  virtualhost:
    fqdn: ingress.vcenter.alb.com
    enableVirtualHost: true
    wafPolicy: System-WAF-Policy
    tls: # optional
      sslKeyCertificate:
        name: System-Default-Cert-EC
        type: ref
#    httpPolicy:
#      policySets:
#        - app-hello-world-HTTPPolicySet-0
    analyticsPolicy: # optional
      fullClientLogs:
        enabled: true
        throttle: HIGH
      logAllHeaders: true