apiVersion: v1
kind: Service
metadata:
  name: web1-infrasetting
  annotations:
    aviinfrasetting.ako.vmware.com/name: "my-infra-setting"
spec:
  loadBalancerClass: ako.vmware.com/avi-lb
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: eighty
  selector:
    app: app-selector-v1