apiVersion: v1
kind: Namespace
metadata:
  name: nested-vcf
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sddcs.nested.vmware.com
spec:
  group: nested.vmware.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                folder:
                  type: string
                domain:
                  type: string
                affinity:
                  type: boolean
                esxi:
                  type: object
                  properties:
                    iso_url:
                      type: string
                    nics:
                      type: array
                      items:
                        type: string
                    ips:
                      type: array
                      items:
                        type: integer
                      minItems: 4
                      multipleOf: 4
                    sizing_mgmt:
                      type: object
                      properties:
                        cpu:
                          type: integer
                        memory:
                          type: integer
                        disk_os_size:
                          type: string
                        disk_flash_size:
                          type: string
                        disk_capacity_size:
                          type: string
                    sizing_workload:
                      type: object
                      properties:
                        cpu:
                          type: integer
                        memory:
                          type: integer
                        disk_os_size:
                          type: string
                        disk_flash_size:
                          type: string
                        disk_capacity_size:
                          type: string
                gw:
                  type: object
                  properties:
                    ova_url:
                      type: string
                    network_ref:
                      type: string
                    ip:
                      type: string
                      format: ipv4
                    dns_forwarders:
                      type: array
                      items:
                        type: string
                        format: ipv4
                    ntp_masters:
                      type: array
                      items:
                        type: string
                cloud_builder:
                  type: object
                  properties:
                    name:
                      type: string
                    ova_url:
                      type: string
                    network_ref:
                      type: string
                    ip:
                      type: string
                      format: ipv4
                sddc:
                  type: object
                  properties:
                    create_mgmt:
                      type: boolean
                    create_wld:
                      type: boolean
                    basename:
                      type: string
                    manager:
                      type: object
                      properties:
                        ip:
                          type: integer
                          format: int32
                          minimum: 2
                          maximum: 253
                    nsx:
                      type: object
                      properties:
                        size:
                          type: string
                        ips:
                          type: array
                          items:
                            type: integer
                            format: int32
                            minimum: 2
                            maximum: 253
                        vip:
                          type: integer
                          format: int32
                          minimum: 2
                          maximum: 253
                        vtep_pool:
                          type: string
                    vcenter:
                      type: object
                      properties:
                        ip:
                          type: integer
                          format: int32
                          minimum: 2
                          maximum: 253
                        vmSize:
                          type: string
                        vsanPool:
                          type: string
                        vmotionPool:
                          type: string
                        ssoDomain:
                          type: string
                        networks:
                          type: array
                          items:
                            type: object
                            properties:
                              type:
                                type: string
                              cidr:
                                type: string
                                pattern: ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}$
                              vlan_id:
                                type: integer
                                minimum: 1
                                maximum: 4094
                    avi:
                      type: object
                      properties:
                        ips:
                          type: array
                          items:
                            type: integer
                            format: int32
                            minimum: 2
                            maximum: 253
                        vip:
                          type: integer
                          format: int32
                          minimum: 2
                          maximum: 253
                vsphere_underlay:
                  type: object
                  properties:
                    vcsa:
                      type: string
                    datacenter:
                      type: string
                    cluster:
                      type: string
                    datastore:
                      type: string
                    networks:
                      type: array
                      items:
                        type: object
                        properties:
                          ref:
                            type: string
                          cidr:
                            type: string
                          gw:
                            type: string
  scope: Namespaced
  names:
    plural: sddcs
    singular: sddc
    kind: sddc
    shortNames:
      - sddc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcf-sa
  namespace: nested-vcf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcf-cr
rules:
  - apiGroups: [""]
    resources: ["events", "pods", "services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["nested.vmware.com"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcf-crb
roleRef:
  kind: ClusterRole
  name: vcf-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vcf-sa
    namespace: nested-vcf