apiVersion: v1
kind: Secret
metadata:
  name: nested-vsphere-external
  namespace: nested-vcf
type: kubernetes.io/basic-auth
stringData:
  username: ${username}
  password: ${password}
---
apiVersion: v1
kind: Secret
metadata:
  name: nested-cloud-builder
  namespace: nested-vcf
type: kubernetes.io/basic-auth
stringData:
  password: ${password}
---
apiVersion: v1
kind: Secret
metadata:
  name: generic-password
  namespace: nested-vcf
type: kubernetes.io/basic-auth
stringData:
  password: ${password}
---
apiVersion: v1
kind: Secret
metadata:
  name: vcf-slack
  namespace: nested-vcf
type: Opaque
stringData:
  webhook_url: ${webhook_url}
---
apiVersion: v1
kind: Secret
metadata:
  name: sddc-manager-depot
  namespace: nested-vcf
type: kubernetes.io/basic-auth
stringData:
  username: username
  password: password