apiVersion: v1
kind: Pod
metadata:
  name: pod-nested-vcf
  namespace: nested-vcf
spec:
  serviceAccountName: vcf-sa
  containers:
    - name: container-nested-vcf
      image: tacobayle/alpine-vcf:latest
      env:
        - name: VSPHERE_EXTERNAL_USERNAME
          valueFrom:
            secretKeyRef:
              name: nested-vsphere-external
              key: username
        - name: VSPHERE_EXTERNAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nested-vsphere-external
              key: password
        - name: EXTERNAL_GW_PASSWORD
          valueFrom:
            secretKeyRef:
              name: external-gw-password
              key: password
        - name: ESXI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nested-esxi
              key: password
        - name: VCENTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nested-vcenter
              key: password
        - name: NSX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nsx
              key: password
        - name: SDDC_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sddc-manager
              key: password
        - name: CLOUD_BUILDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nested-cloud-builder
              key: password
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: vcf-slack
              key: webhook_url
  restartPolicy: Never