apiVersion: v1
kind: Pod
metadata:
  name: pod-nested-vcf
  namespace: nested-vcf
spec:
  serviceAccountName: vcf-sa
  containers:
    - name: container-nested-vcf
      image: tacobayle/alpine-vcf:latest
      env:
        - name: VSPHERE_EXTERNAL_USERNAME
          valueFrom:
            secretKeyRef:
              name: nested-vsphere-external
              key: username
        - name: VSPHERE_EXTERNAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nested-vsphere-external
              key: password
        - name: GENERIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: generic-password
              key: password
        - name: CLOUD_BUILDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nested-cloud-builder
              key: password
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: vcf-slack
              key: webhook_url
        - name: DEPOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: sddc-manager-depot
              key: username
        - name: DEPOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sddc-manager-depot
              key: password
  restartPolicy: Never