apiVersion: nested.vmware.com/v1alpha1
kind: sddc
metadata:
  name: sddc-mgmt
  namespace: nested-vcf
spec:
  folder: nic-nested-vcf
  domain: sddc.com
  affinity: true
  gw:
    ova_url: http://10.6.248.79:8000/focal-server-cloudimg-amd64.ova
    network_ref: ams-cm2w1-nsx1-avi-mgmt
    ip: 10.6.248.70
    name: nic-mgmt-esxi-external-gw
    dns_forwarders:
      - 192.19.189.10
    ntp_masters:
      - ntp.broadcom.net
  esxi:
    iso_url: http://10.6.248.79:8000/VMware-VMvisor-Installer-8.0U3-24022510.x86_64.iso
    ips:
      - 11
      - 12
      - 13
      - 14
      - 21
      - 22
      - 23
      - 24
    sizing_mgmt:
      cpu: 24
      memory: 131072 # in MB
      disk_os_size: 32G
      disk_flash_size: 64G
      disk_capacity_size: 448G
    sizing_workload:
      cpu: 8
      memory: 32768 # in MB
      disk_os_size: 32G
      disk_flash_size: 16G
      disk_capacity_size: 112G
    nics:
      - nic-trunk-1
      - nic-trunk-2
  cloud_builder:
    name: vcf-cloud-builder
    ova_url: http://10.6.248.79:8000/VMware-Cloud-Builder-5.2.0.0-24108943_OVF10.ova
    network_ref: ams-cm2w1-nsx1-avi-mgmt
    ip: 10.6.248.71
  sddc:
    create_mgmt: true
    create_wld: true
    basename: sddc01
    manager:
      ip: 172.16.4.11
    nsx:
      size: medium
      ips:
        - 172.16.4.13
      vip: 172.16.4.14
      vtep_pool: 172.16.5.101-172.16.5.109
    vcenter:
      ip: 172.16.4.12
      vmSize: "small"
      ssoDomain: "vsphere.local"
      vsanPool: 172.16.2.101-172.16.2.109
      vmotionPool: 172.16.3.101-172.16.3.109
      networks:
        - type: MANAGEMENT
          cidr: 172.16.1.0/24
          gw: 172.16.1.1
          vlan_id: 2048
        - type: VSAN
          cidr: 172.16.2.0/24
          gw: 172.16.2.1
          vlan_id: 2049
        - type: VMOTION
          cidr: 172.16.3.0/24
          gw: 172.16.3.1
          vlan_id: 2050
        - type: VM_MANAGEMENT
          cidr: 172.16.4.0/24
          gw: 172.16.4.1
          vlan_id: 2051
        - type: HOST_OVERLAY
          cidr: 172.16.5.0/24
          gw: 172.16.5.1
          vlan_id: 2052
        - type: EDGE_OVERLAY
          cidr: 172.16.6.0/24
          gw: 172.16.6.1
          vlan_id: 2053
  vsphere_underlay:
    vcsa: https://ams-cm2w1-vc1.ams.broadcom.net
    datacenter: ams-cm2w1-vc1
    cluster: ams-cm2w1-vc1-c1
    datastore: ams-cm2w1-vc1-c1-vsan
    networks:
      - ref: ams-cm2w1-nsx1-avi-mgmt
        cidr: 10.6.248.0/24
        gw: 10.6.248.1