apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-vsphere
  namespace: default
data:
  variables.json: |
    {
      "vsphere_underlay": {
        "vcsa": "sof2-01-vc08.oc.vmware.com",    
        "datacenter": "sof2-01-vc08",
        "cluster": "sof2-01-vc08c01",
        "datastore": "sof2-01-vc08c01-vsan",
        "folder": "nic-vsphere",
        "networks_vsphere_dual_attached": true,
        "networks": {
          "vsphere": {
            "management": {
              "name": "vxw-dvs-34-virtualwire-3-sid-1080002-sof2-01-vc08-avi-mgmt",
              "cidr": "10.41.132.0/22",
              "gateway": "10.41.132.1",
              "esxi_ips": ["10.41.134.211", "10.41.134.212", "10.41.134.213"],
              "esxi_ips_temp": ["10.41.134.120", "10.41.134.121", "10.41.134.122"],
              "external_gw_ip": "10.41.134.210",
              "vcsa_nested_ip": "10.41.134.214"
            },
            "vmotion": {
              "name": "vxw-dvs-34-virtualwire-119-sid-1080118-sof2-01-vc08-avi-dev115",
              "esxi_ips": ["100.64.132.31", "100.64.132.32", "100.64.132.33"],
              "cidr": "100.64.132.0/24"
            },
            "vsan": {
              "name": "vxw-dvs-34-virtualwire-120-sid-1080119-sof2-01-vc08-avi-dev116",
              "esxi_ips": ["100.64.133.31", "100.64.133.32", "100.64.133.33"],
              "cidr": "100.64.133.0/24"
            }
          }
        }
      },
      "external_gw": {
        "bind": {
          "forwarders": ["10.23.108.1", "10.23.108.2", "10.16.142.111"],
          "domain": "alb123.com"
        },
        "ntp": "time.vmware.com"
      },
      "vsphere_nested": {
        "vcsa_name": "vcsa-01",
        "iso_url": "http://10.41.135.46:8000/VMware-VCSA-all-8.0.2-22617221.iso",
        "datacenter": "dc1",
        "cluster_basename": "cluster-",
        "cluster_esxi_count": 3,
        "sso": {
          "domain_name": "domain.local"
        },
        "timezone": "Europe/Paris",
        "esxi": {
          "iso_url": "http://10.41.135.46:8000/VMware-VMvisor-Installer-8.0U2-22380479.x86_64.iso",
          "basename": "esxi-0",
          "cpu": 24,
          "memory": 131072,
          "disks_description": "",
          "disks": [
            {
              "size": 32,
              "thin_provisioned": true
            },
            {
              "size": 64,
              "thin_provisioned": true
            },
            {
              "size": 448,
              "thin_provisioned": true
            }
          ]
        }
      }
    }
