apiVersion: v1
kind: Secret
metadata:
  name: vsphere-underlay
type: kubernetes.io/basic-auth
stringData:
  username: "******"
  password: "******"
---
apiVersion: v1
kind: Secret
metadata:
  name: ubuntu-password
type: kubernetes.io/basic-auth
stringData:
  password: "******"
---
apiVersion: v1
kind: Secret
metadata:
  name: bind-password
type: kubernetes.io/basic-auth
stringData:
  password: "******"
---
apiVersion: v1
kind: Secret
metadata:
  name: nested-esxi
type: kubernetes.io/basic-auth
stringData:
  username: "******"
  password: "******"
---
apiVersion: v1
kind: Secret
metadata:
  name: nested-vsphere
type: kubernetes.io/basic-auth
stringData:
  password: "******"