apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: folders.vsphere.com
spec:
  group: vsphere.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                data:
                  type: string
  scope: Namespaced
  names:
    plural: folders
    singular: folder
    kind: ExternalResource
    shortNames:
      - f
