apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vsphere-folders.nested.vmware.com
spec:
  group: nested.vmware.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
  scope: Namespaced
  names:
    plural: vsphere-folders
    singular: vsphere-folder
    kind: vsphere-folder
    shortNames:
      - vsf