---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-test
spec:
  containers:
    - name: container-test
      image: alpine:3.20
      command: [ "/bin/sh", "-c", "while true ; do sleep 3600 ; done" ]
  imagePullSecrets:
    - name: docker
  restartPolicy: Never