apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: tacobayle/ubuntu-automation:latest
      command: [ "/bin/sh", "-c", "/bin/bash /build/apply.sh" ]
      env:
        - name: TF_VAR_vsphere_underlay_username
          valueFrom:
            secretKeyRef:
              name: vsphere-underlay
              key: username
        - name: TF_VAR_vsphere_underlay_password
          valueFrom:
            secretKeyRef:
              name: vsphere-underlay
              key: password
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: json-configmap
  restartPolicy: Never
